{

  age.alice.public = ./age-alice-public.txt;
  age.alice.private = ./age-alice-private.txt;

  ed25519.alice.public = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKWpfDJ/8B3QpB2qUmgFio0TaV0ulAaNc0eKAxC5FiK/";
  ed25519.alice.private = ''
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACClqXwyf/Ad0KQdqlJoBYqNE2ldLpQGjXNHigMQuRYivwAAAJiTUdVlk1HV
    ZQAAAAtzc2gtZWQyNTUxOQAAACClqXwyf/Ad0KQdqlJoBYqNE2ldLpQGjXNHigMQuRYivw
    AAAEAA/W+k/Uecrh5L6AgzkmJxIv04WbJkp7i9SO3gmpKRDKWpfDJ/8B3QpB2qUmgFio0T
    aV0ulAaNc0eKAxC5FiK/AAAAEWFhYmNjZDAyMUBkZXNrdG9wAQIDBA==
    -----END OPENSSH PRIVATE KEY-----
  '';

  ed25519.bob.public = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEy2bFKXQMLypMyNYIZSBwsSUzDrD6YmBWoF99M5It4x";
  ed25519.bob.private = ''
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBMtmxSl0DC8qTMjWCGUgcLElMw6w+mJgVqBffTOSLeMQAAAJhcpeAtXKXg
    LQAAAAtzc2gtZWQyNTUxOQAAACBMtmxSl0DC8qTMjWCGUgcLElMw6w+mJgVqBffTOSLeMQ
    AAAECl78pyKT6/Scktz8gPBd9f9XIN1iG98MSJlnX0wKI9Aky2bFKXQMLypMyNYIZSBwsS
    UzDrD6YmBWoF99M5It4xAAAAEWFhYmNjZDAyMUBkZXNrdG9wAQIDBA==
    -----END OPENSSH PRIVATE KEY-----
  '';

}
